# Minecraft Java Paper Server Docker Container - Docker Compose
# Author: James A. Chambers - https://jamesachambers.com/legendary-paper-minecraft-java-container/
# GitHub Repository: https://github.com/TheRemote/Legendary-Java-Minecraft-Paper

# To run multiple servers change the volume name under both "volumes" sections and select different ports
version: "3.5"
services:
  minecraftbe:
    image: 05jchambers/legendary-java-minecraft-paper:latest
    restart: "unless-stopped"
    ports:
      - 25565:25565
    volumes:
      - minecraft:/minecraft
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: [ "/bin/bash", "/scripts/start.sh" ]
    environment:
      Port: "25565"
      TZ: "America/Denver" # timezone
      #BackupCount: 10 # Number of backups the server keeps
      #MaxMemory: 2048 # Maximum memory usage for Java
      #Version: 1.19.3 # Use custom version
      #NoBackup: "plugins" # Optional folder to skip during backups
      #NoPermCheck: "Y" # Optional flag to skip permissions check
      #QuietCurl: "Y" # Optional flag to reduce curl log output by suppressing progress meter
volumes:
  minecraft:
    driver: local
